<?php

namespace Database\Seeders;

use App\Models\Laporan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LaporanSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $data = [
      // 1. Paket Penyedia
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat Tulis Kantor',
        'pagu'                               => 1684800,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => null,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Belanja Alat/Bahan untuk Kegiatan Kantor-Bahan Cetak',
        'pagu'                               => 1640520,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => null,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Belanja Makanan dan Minuman Rapat',
        'pagu'                               => 5040000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => null,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Kantor',
        'pagu'                               => 1220400,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => null,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Fotocopy',
        'pagu'                               => 1033620,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => 320000,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => 570500,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => 0.81,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Cetak Spanduk',
        'pagu'                               => 4032000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => 4032000,
        'presentasi_realisasi_fisik'         => null,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 3,
        'nama_pekerjaan'                     => 'Belanja Makanan dan Minuman Jamuan Tamu',
        'pagu'                               => 6580000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => null,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => 2769000,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => 0.44,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],

      // 2. Paket Swakelola
      [
        'kategori_laporan_id'                => 4,
        'nama_pekerjaan'                     => 'Belanja Lembur',
        'pagu'                               => 35877000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => 20142000,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => 0.6,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 4,
        'nama_pekerjaan'                     => 'Belanja Bimbingan Teknis',
        'pagu'                               => 62349000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => 20651360,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => 1.25,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 4,
        'nama_pekerjaan'                     => 'Belanja Perjalanan Dinas Biasa',
        'pagu'                               => 52844000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => 37900700,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => 0.75,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 4,
        'nama_pekerjaan'                     => 'Belanja Perjalanan Dinas Dalam Kota',
        'pagu'                               => 18720000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => 15600000,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => null,
        'presentasi_realisasi_fisik'         => 0.833,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
      [
        'kategori_laporan_id'                => 4,
        'nama_pekerjaan'                     => 'Belanja Jasa Tenaga Penanganan Prasarana dan Sarana Umum',
        'pagu'                               => 56000000,
        'no_kontrak'                         => null,
        'tgl_mulai_kontrak'                  => null,
        'tgl_berakhir_kontrak'               => null,
        'nilai_kontrak_tender'               => null,
        'realisasi_tender'                   => null,
        'nilai_kontrak_penunjukkan_langsung' => null,
        'realisasi_penunjukkan_langsung'     => null,
        'nilai_kontrak_swakelola'            => null,
        'realisasi_swakelola'                => 26000000,
        'nilai_kontrak_epurchasing'          => null,
        'realisasi_epurchasing'              => null,
        'nilai_kontrak_pengadaan_langsung'   => null,
        'realisasi_pengadaan_langsung'       => 15000000,
        'presentasi_realisasi_fisik'         => 0.583,
        'sumber_dana'                        => null,
        'keterangan'                         => null,
      ],
    ];

    foreach ($data as $item) {
      Laporan::create($item);
    }
  }
}
