<?php

namespace Database\Seeders;

use App\Models\SKPD;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class SKPDSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $data = [
      [
        'nama'                   => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
        'singkatan'              => 'BKPSDM',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Kesatuan Bangsa dan Politik',
        'singkatan'              => 'Bakesbangpol',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Penanggulangan Bencana Daerah',
        'singkatan'              => 'BPBD',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Pendapatan Daerah',
        'singkatan'              => 'Bapenda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Keuangan dan Aset Daerah',
        'singkatan'              => 'BKAD',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Perencanaan Pembangunan Daerah',
        'singkatan'              => 'Bappeda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pemadam Kebakaran dan Penyelamatan',
        'singkatan'              => 'Disdamkar',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pariwisata dan Ekonomi Kreatif',
        'singkatan'              => 'Disparekraf',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Perikanan',
        'singkatan'              => 'Diskan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Kependudukan dan Pencatatan Sipil',
        'singkatan'              => 'Disdukcapil',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Kesehatan',
        'singkatan'              => 'Dinkes',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Komunikasi dan Informatika',
        'singkatan'              => 'Diskominfo',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Lingkungan Hidup dan Kehutanan',
        'singkatan'              => 'DLHK',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Ketahanan Pangan',
        'singkatan'              => 'DKP',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pemberdayaan Perempuan dan Perlindungan Anak',
        'singkatan'              => 'DP3A',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
        'singkatan'              => 'DPMPTSP',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pendidikan dan Kebudayaan',
        'singkatan'              => 'Disdikbud',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pengendalian Penduduk dan Keluarga Berencana',
        'singkatan'              => 'DPPKB',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Perdagangan, Koperasi, Usaha Kecil Dan Menengah',
        'singkatan'              => 'Disdagkop-UKM',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [ // skpd_id = 20
        'nama'                   => 'Dinas Perhubungan',
        'singkatan'              => 'Dishub',
        'alamat'                 => null,
        'pimpinan_skpd'          => 'PAMINUDDIN, SE., M.Si.',
        'nip_pimpinan'           => '196909101993121001',
        'pangkat_pimpinan'       => 'Pembina Utama Muda',
        'golongan_pimpinan'      => 'IV/c',
        'jenis_kelamin_pimpinan' => 'L',
        'kontak_pimpinan'        => '081341770730',
      ],
      [
        'nama'                   => 'Dinas Perpustakaan dan Kearsipan Daerah',
        'singkatan'              => 'Dispusipda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pertanian',
        'singkatan'              => 'Distan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Perumahan, Kawasan Permukiman dan Pertanahan',
        'singkatan'              => 'Disperkimtan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pekerjaan Umum dan Penataan Ruang',
        'singkatan'              => 'Dinas PUPR',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Sosial',
        'singkatan'              => 'Dinsos',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Tenaga Kerja dan Perindustrian',
        'singkatan'              => 'Disnakerperin',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Inspektorat Daerah',
        'singkatan'              => 'Inspektorat',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pemuda dan Olahraga',
        'singkatan'              => 'Diaspora',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Abeli',
        'singkatan'              => 'Kec. Abeli',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Baruga',
        'singkatan'              => 'Kec. Baruga',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Kadia',
        'singkatan'              => 'Kec. Kadia',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Kambu',
        'singkatan'              => 'Kec. Kambu',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Kendari',
        'singkatan'              => 'Kec. Kendari',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Kendari Barat',
        'singkatan'              => 'Kec. Kendari Barat',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Mandonga',
        'singkatan'              => 'Kec. Mandonga',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Nambo',
        'singkatan'              => 'Kec. Nambo',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Poasia',
        'singkatan'              => 'Kec. Poasia',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Puwatu',
        'singkatan'              => 'Kec. Puwatu',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Wua-Wua:',
        'singkatan'              => 'Kec. Wua-Wua:',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'RSUD Kota Kendari',
        'singkatan'              => 'RSUD Kendari',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Satuan Polisi Pamong Praja',
        'singkatan'              => 'Satpol PP',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Sekretariat DPRD',
        'singkatan'              => 'Setwan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'RSUD Antero Hamra Kota Kendari',
        'singkatan'              => 'RSUD Antero Hamra',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Sekretariat Daerah',
        'singkatan'              => 'Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],

    ];

    foreach ($data as $item) {
      // 1. Buat SKPD terlebih dahulu
      $skpd = SKPD::create($item);

      // 2. Siapkan data user secara dinamis berdasarkan 'singkatan'
      $username = Str::replace('-', '_', Str::lower($item['singkatan']));

      $userData = [
        'name'      => 'Admin ' . $item['singkatan'],
        'username'  => $username,
        'email'     => $username . '@example.com',
        'password'  => Hash::make($username),
        'skpd_id'   => $skpd->id,
        'role'      => 'skpd',
      ];

      // 3. Buat user
      User::create($userData);
    }
  }
}
