<?php

namespace Database\Seeders;

use App\Models\SKPD;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class SKPDSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $data = [
      [
        'nama'                   => 'Dinas Perhubungan',
        'singkatan'              => 'Dishub',
        'alamat'                 => null,
        'pimpinan_skpd'          => 'Paminuddin, SE., M.Si.',
        'nip_pimpinan'           => '196909101993121001',
        'pangkat_pimpinan'       => 'Pembina Utama Muda',
        'golongan_pimpinan'      => 'IV/c',
        'jenis_kelamin_pimpinan' => 'L',
        'kontak_pimpinan'        => '081341770730',
      ],
      [
        'nama'                   => 'Dinas Perpustakaan dan Kearsipan Daerah',
        'singkatan'              => 'Dispusipda',
        'alamat'                 => null,
        'pimpinan_skpd'          => 'Hj. Andi Dadjeng, SE',
        'nip_pimpinan'           => '196601171991032005',
        'pangkat_pimpinan'       => 'Pembina Utama Muda',
        'golongan_pimpinan'      => 'IV/c',
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Ketahanan Pangan',
        'singkatan'              => 'DKP',
        'alamat'                 => null,
        'pimpinan_skpd'          => 'Drs. Abdul Rauf',
        'nip_pimpinan'           => '196808151998031007',
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => 'L',
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Dinas Pangan',
          'username' => 'dinaspangan',
          'password' => Hash::make('dinaspangan'),
          'email'    => 'dinaspangan@example.com',
        ]
      ],
      [
        'nama'                   => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
        'singkatan'              => 'BKPSDM',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Kesatuan Bangsa dan Politik',
        'singkatan'              => 'Bakesbangpol',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Penanggulangan Bencana Daerah',
        'singkatan'              => 'BPBD',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Pendapatan Daerah',
        'singkatan'              => 'Bapenda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Keuangan dan Aset Daerah',
        'singkatan'              => 'BKAD',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Badan Perencanaan Pembangunan Daerah',
        'singkatan'              => 'Bappeda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pemadam Kebakaran dan Penyelamatan',
        'singkatan'              => 'Disdamkar',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pariwisata dan Ekonomi Kreatif',
        'singkatan'              => 'Disparekraf',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Perikanan',
        'singkatan'              => 'Diskan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Kependudukan dan Pencatatan Sipil',
        'singkatan'              => 'Disdukcapil',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Kesehatan',
        'singkatan'              => 'Dinkes',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Komunikasi dan Informatika',
        'singkatan'              => 'Diskominfo',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Lingkungan Hidup dan Kehutanan',
        'singkatan'              => 'DLHK',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pemberdayaan Perempuan dan Perlindungan Anak',
        'singkatan'              => 'DP3A',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
        'singkatan'              => 'DPMPTSP',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pendidikan dan Kebudayaan',
        'singkatan'              => 'Disdikbud',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pengendalian Penduduk dan Keluarga Berencana',
        'singkatan'              => 'DPPKB',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Perdagangan, Koperasi, Usaha Kecil Dan Menengah',
        'singkatan'              => 'Disdagkop-UKM',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Disdagkop-UKM',
          'username' => 'disdagkop',
          'password' => Hash::make('disdagkop'),
          'email'    => 'disdagkop@example.com',
        ]
      ],
      [
        'nama'                   => 'Dinas Pertanian',
        'singkatan'              => 'Distan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Perumahan, Kawasan Permukiman dan Pertanahan',
        'singkatan'              => 'Disperkimtan',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pekerjaan Umum dan Penataan Ruang',
        'singkatan'              => 'Dinas PUPR',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Dinas PUPR',
          'username' => 'pupr',
          'password' => Hash::make('pupr'),
          'email'    => 'pupr@example.com',
        ]
      ],
      [
        'nama'                   => 'Dinas Sosial',
        'singkatan'              => 'Dinsos',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Tenaga Kerja dan Perindustrian',
        'singkatan'              => 'Disnakerperin',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Inspektorat Daerah',
        'singkatan'              => 'Inspektorat',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Dinas Pemuda dan Olahraga',
        'singkatan'              => 'Diaspora',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
      ],
      [
        'nama'                   => 'Kecamatan Abeli',
        'singkatan'              => 'Kec. Abeli',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Abeli',
          'username' => 'kecabeli',
          'password' => Hash::make('kecabeli'),
          'email'    => 'kecabeli@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Baruga',
        'singkatan'              => 'Kec. Baruga',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Baruga',
          'username' => 'kecbaruga',
          'password' => Hash::make('kecbaruga'),
          'email'    => 'kecbaruga@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Kadia',
        'singkatan'              => 'Kec. Kadia',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Kadia',
          'username' => 'keckadia',
          'password' => Hash::make('keckadia'),
          'email'    => 'keckadia@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Kambu',
        'singkatan'              => 'Kec. Kambu',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Kambu',
          'username' => 'keckambu',
          'password' => Hash::make('keckambu'),
          'email'    => 'keckambu@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Kendari',
        'singkatan'              => 'Kec. Kendari',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Kendari',
          'username' => 'keckendari',
          'password' => Hash::make('keckendari'),
          'email'    => 'keckendari@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Kendari Barat',
        'singkatan'              => 'Kec. Kendari Barat',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Kendari Barat',
          'username' => 'keckendaribarat',
          'password' => Hash::make('keckendaribarat'),
          'email'    => 'keckendaribarat@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Mandonga',
        'singkatan'              => 'Kec. Mandonga',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Mandonga',
          'username' => 'kecmandonga',
          'password' => Hash::make('kecmandonga'),
          'email'    => 'kecmandonga@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Nambo',
        'singkatan'              => 'Kec. Nambo',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Nambo',
          'username' => 'kecnambo',
          'password' => Hash::make('kecnambo'),
          'email'    => 'kecnambo@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Poasia',
        'singkatan'              => 'Kec. Poasia',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Poasia',
          'username' => 'kecpoasia',
          'password' => Hash::make('kecpoasia'),
          'email'    => 'kecpoasia@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Puwatu',
        'singkatan'              => 'Kec. Puwatu',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Puwatu',
          'username' => 'kecpuwatu',
          'password' => Hash::make('kecpuwatu'),
          'email'    => 'kecpuwatu@example.com',
        ]
      ],
      [
        'nama'                   => 'Kecamatan Wua-Wua',
        'singkatan'              => 'Kec. Wua-Wua',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Kec. Wua-Wua',
          'username' => 'kecwuawua',
          'password' => Hash::make('kecwuawua'),
          'email'    => 'kecwuawua@example.com',
        ]
      ],
      [
        'nama'                   => 'RSUD Kota Kendari',
        'singkatan'              => 'RSUD Kendari',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin RSUD Kendari',
          'username' => 'rsudkendari',
          'password' => Hash::make('rsudkendari'),
          'email'    => 'rsudkendari@example.com',
        ]
      ],
      [
        'nama'                   => 'Satuan Polisi Pamong Praja',
        'singkatan'              => 'Satpol PP',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin PolPP',
          'username' => 'polpp',
          'password' => Hash::make('polpp'),
          'email'    => 'polpp@example.com',
        ]
      ],
      [
        'nama'                   => 'Sekretariat DPRD',
        'singkatan'              => 'DPRD',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin DPRD',
          'username' => 'dprd',
          'password' => Hash::make('dprd'),
          'email'    => 'dprd@example.com',
        ]
      ],
      [
        'nama'                   => 'RSUD Antero Hamra Kota Kendari',
        'singkatan'              => 'RSUD Antero Hamra',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin RSUD Antero Hamra',
          'username' => 'rsudantero',
          'password' => Hash::make('rsudantero'),
          'email'    => 'rsudantero@example.com',
        ]
      ],

      [
        'nama'                   => 'Bagian Administrasi Pembangunan Setda',
        'singkatan'              => 'Bagian Administrasi Pembangunan Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => 'M. Ibrahim Muis, S.Sos.',
        'nip_pimpinan'           => '197011162000031004',
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => 'L',
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Pembangunan Setda',
          'username' => 'pembsetda',
          'password' => Hash::make('pembsetda'),
          'email'    => 'pembsetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Sumber Daya Alam Setda',
        'singkatan'              => 'Bagian Sumber Daya Alam Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin SDA Setda',
          'username' => 'sdasetda',
          'password' => Hash::make('sdasetda'),
          'email'    => 'sdasetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Kerjasama Setda',
        'singkatan'              => 'Bagian Kerjasama Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Kerjasama Setda',
          'username' => 'kerjasamasetda',
          'password' => Hash::make('kerjasamasetda'),
          'email'    => 'kerjasamasetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Perekonomian Setda',
        'singkatan'              => 'Bagian Perekonomian Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Perekonomian Setda',
          'username' => 'ekonomisetda',
          'password' => Hash::make('ekonomisetda'),
          'email'    => 'ekonomisetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Kesejahteraan Rakyat Setda',
        'singkatan'              => 'Bagian Kesejahteraan Rakyat Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Kesejahteraan Setda',
          'username' => 'kesejahteraansetda',
          'password' => Hash::make('kesejahteraansetda'),
          'email'    => 'kesejahteraansetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Organisasi Setda',
        'singkatan'              => 'Bagian Organisasi Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Organisasi Setda',
          'username' => 'organisasisetda',
          'password' => Hash::make('organisasisetda'),
          'email'    => 'organisasisetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Pengadaan Barang dan Jasa Setda',
        'singkatan'              => 'Bagian Pengadaan Barang dan Jasa Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Pengadaan Barang Jasa Setda',
          'username' => 'barangjasasetda',
          'password' => Hash::make('barangjasasetda'),
          'email'    => 'barangjasasetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Perencanaan dan Keuangan Setda',
        'singkatan'              => 'Bagian Perencanaan dan Keuangan Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Keuangan Setda',
          'username' => 'keuangansetda',
          'password' => Hash::make('keuangansetda'),
          'email'    => 'keuangansetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Protokol dan Komunikasi Pimpinan Setda',
        'singkatan'              => 'Bagian Protokol dan Komunikasi Pimpinan Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Protokol Komunikasi Pimpinan Setda',
          'username' => 'prokumsetda',
          'password' => Hash::make('prokumsetda'),
          'email'    => 'prokumsetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Tata Pemerintahan Setda',
        'singkatan'              => 'Bagian Tata Pemerintahan Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Pemerintahan Setda',
          'username' => 'pemerintahansetda',
          'password' => Hash::make('pemerintahansetda'),
          'email'    => 'pemerintahansetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Umum Setda',
        'singkatan'              => 'Bagian Umum Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Umum Setda',
          'username' => 'umumsetda',
          'password' => Hash::make('umumsetda'),
          'email'    => 'umumsetda@example.com',
        ]
      ],
      [
        'nama'                   => 'Bagian Hukum Setda',
        'singkatan'              => 'Bagian Hukum Setda',
        'alamat'                 => null,
        'pimpinan_skpd'          => null,
        'nip_pimpinan'           => null,
        'pangkat_pimpinan'       => null,
        'golongan_pimpinan'      => null,
        'jenis_kelamin_pimpinan' => null,
        'kontak_pimpinan'        => null,
        'users'                  => [
          'name'     => 'Admin Bagian Hukum Setda',
          'username' => 'hukumsetda',
          'password' => Hash::make('hukumsetda'),
          'email'    => 'hukumsetda@example.com',
        ]
      ],
    ];

    foreach ($data as $item) {
      // 1. Buat SKPD terlebih dahulu
      $skpdItem = Arr::except($item, ['users']);
      $newSkpd  = SKPD::create($skpdItem);

      if (array_key_exists('users', $item) && !empty($item['users'])) {
        $userData            = $item['users'];
        $userData['skpd_id'] = $newSkpd->id;
      } else {
        $username = Str::replace('-', '_', Str::lower($item['singkatan']));
        $userData = [
          'name'      => 'Admin ' . $item['singkatan'],
          'username'  => Str::lower($item['singkatan']),
          'email'     => $username . '@example.com',
          'password'  => Hash::make($username),
          'skpd_id'   => $newSkpd->id,
        ];
      }

      // 3. Buat user
      User::create($userData);
    }
  }
}
